#!/bin/sh
clear
mkdir -p kernel/usr/initramfs
rm -r -f kernel/usr/initramfs/*
cp -R ../GalaxyPlayer5-initrd/* kernel/usr/initramfs
rm $(find kernel/usr/initramfs -name EMPTY_DIRECTORY -print)
rm -rf $(find kernel/usr/initramfs -name .git -print)
make ac_usa_defconfig
#get rid of the damn + after the version
export LOCALVERSION=""
make -j8 && cp -a $(find . -name *.ko -print |grep -v initramfs) kernel/usr/initramfs/lib/modules/ && make -j8
# adb shell reboot download
# sleep 5
# heimdall flash --kernel arch/arm/boot/zImage
